config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :trainings do
    resources :exercises
  end

  resources :nutritions do
    resources :meals
  end
  
  root 'welcome#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :training
  has_many :wosets

  accepts_nested_attributes_for :wosets,
  								reject_if: proc {|attributes| attributes['weight','reps'].blank?},
  								allow_destroy: true
 validates :weight, :reps, presence: true
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :nutrition
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
  has_many :meals
end

app/models/rep.rb
class Rep < ActiveRecord::Base
  belongs_to :wosets
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :exercises
  #has_attached_file :image, :styles => { :medium => "300x300#>"}
  #validates_attachment_content_type :image, :content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/woset.rb
class Woset < ActiveRecord::Base
  belongs_to :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	before_action :find_exercise, only:[:show, :edit, :update, :destroy]
	def index
		@exercses = Exercise.all.order("created_at DESC")
	end

	def new
		@exercise = Exercise.new
	end

	def create
		@exercise = Exercise.new(exercise_params)
		if @exercise.save
			redirect_to @exercise, notice: "Exercise created"
		else
			redirect_to trainings_path
		end
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
		@exercise.destroy
			redirect_to exercises_path, notice: "Exercise deleted"
	end

	private

	def exercise_params
		params.require(:exercises).permit(:name, :notes, wostes_attributes:[:id, :weight,:reps,:notes, :_destroy])
	end

	def find_exercise
		@exercies= Exercise.find(params[:id])
	end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
   def create
    @nutrition = Nutrition.find(params[:nutrition_id])
    @meal = @nutrition.meals.create(params[:meal].permit(:feast, :name, :protein, :carbohydrates, :fat, :calories, :notes, :date))

    redirect_to nutrition_path(@nutrition)
  end
end

app/controllers/nutritions_controller.rb
class NutritionsController < ApplicationController
  before_action :find_nutrition, only: [:show, :edit, :update, :destroy]

  def index
    @nutritions = Nutrition.all.order("created_at DESC")
  end

  def show
  end

  def new
    @nutrition = Nutrition.new
  end

  def create
    @nutrition = Nutrition.new(nutrition_params)
    if @nutrition.save
      redirect_to @nutrition
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @nutrition = Nutrition.update(nutrition_params)
    redirect_to @nutrition
  end

  def destroy
    @nutrition.destroy
    redirect_to root_path
  end

  private

  def find_nutrition
    @nutrition = Nutrition.find(params[:id])
  end

  def nutrition_params
    params.require(:nutrition).permit(:name, :date)
  end


end

app/controllers/reps_controller.rb
class RepsController < ApplicationController
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :find_trainings, only: [:show, :edit, :update, :destroy]
  def index
    @trainings = Training.all.order("created_at DESC")
  end

  def show
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(trainings_params)

    if @training.save
      redirect_to @training, notice: "Succesfully created new Workout"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @training.update(trainings_params)
      redirect_to @training
    else
      render 'edit'
    end
  end

  def destroy
    @training.destroy
        redirect_to trainings_path, notice: "Succesfully Deleted Workout"
  end

private

  def find_trainings
    @training = Training.find(params[:id])
  end

   def trainings_params
    params.require(:training).permit(:date, :name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wosets_controller.rb
class WosetsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/nutritions_helper.rb
module NutritionsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wosets_helper.rb
module WosetsHelper
end

app/views/meals/_form.html.erb
<%= simple_form_for([@nutrition, @nutrition.meals.build]) do |f| %> 
<br>
<small><em>add time here later</em></small>
  <h4><strong>Type of Meal</strong><small> (Breakfast, lunch etc...)</small></h4>
  <h4><%= f.input :feast, label: false %></h4>

  <h4><%= f.input :name%></h4>
  
  <h4><%= f.input :protein%> g</h4>
  

  <h4><%= f.input :carbohydrates%> g</h4>
  

  <h4><%= f.input :fat%> g</h4>
  

  <h4><%= f.input :calories%> cal</h4>
  

  <h4><%= f.input :notes%></h4>
  
  <br>

  <%= f.button :submit%>
  <% end %>
  <br>

<%= link_to "Cancel", root_path %>

app/views/meals/_meal.html.erb
<h3><strong><%= meal.feast %></strong></h3>

<h4>Name</h4>
<p><%= meal.name %></p>

<h4>Protein</h4>
<p><%= meal.protein %>g</p>

<h4>Carbohydrates</h4>
<p><%= meal.carbohydrates %>g</p>

<h4>Fat</h4>
<p><%= meal.fat %>g</p>

<h4>Calories</h4>
<p><%= meal.calories %>cal</p>
<br><br>

<h3>total protein 
<% @meal.each do |m|  %>
  <%= m.protein %>
<%end%>
</h3>

app/views/nutritions/_form.html.erb
<%= simple_form_for(@nutrition, html: { class: 'form-vertical' }) do |f| %>
<div class="container">

  <h3>Date</h3>
  <%= f.input :date%>
  <h3>Name <small><i>Optional</i></small></h3>
  <%= f.input :name%>

  <br>

  <%= f.button :submit, class: 'btn btn-success'%>
  <% end %>

<%= link_to "Cancel", root_path, class: 'btn btn-danger' %>
</div>

app/views/nutritions/index.html.erb
<h1>Meals Index</h1>
<% @nutritions.each do |t| %>
  <%= link_to t.date.strftime("%A %B, %d"),t %>
  <small><i><%= t.name %></i></small>
  <br>
<% end %>

<h5>Total Protein | Total Carbs | Total Fat | Total Calories</h5>
      


<%= link_to 'New', new_nutrition_path %>

app/views/nutritions/new.html.erb
<%= render 'form' %>

app/views/nutritions/show.html.erb
<div class="container">
  <h2><p><%= @nutrition.name %></p></h2>
      <p><%= @nutrition.date.strftime("%A %B, %d") %></p>
      
    <br>
    <%= render @nutrition.meals %>
    <br>
    
    <%= render "meals/form" %>

  <%= link_to "Back", nutritions_path %> |
  <%= link_to "Edit", edit_nutrition_path(@nutrition) %> |
  <%= link_to "Delete", nutrition_path(@nutrition), method: :delete, data: {confirm: "Are you sure?"}%>
</div>

app/views/trainings/_form.html.haml
= simple_form_for @training, html: {multipart: true} do |f|
  - if @training.errors.any?
    #errors
      %p
        = @training.errors.count
        Prevented this Workout from saving
      %ul
        - @training.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :date, input_html: {class: 'form-control'}
    = f.input :name, input_html: {class: 'form-control'}
    = f.input :description, input_html: {class: 'form-control'}

  = f.button :submit, class: "btn btn-primary"

app/views/trainings/edit.html.haml
%h1 Edit
= render = 'form'

= link_to "Back", root_path, class: "btn btn-default"

app/views/trainings/index.html.erb
<h1> Training page</h1>

<p>
  <%= link_to "New Workout", new_training_path %>
  </br>
    <% @trainings.each do |f| %>
  </br>
    <%= link_to f.date, f %>
  </br>
    <small><%= f.name %></small>
    
  <% end %>
</p>

app/views/trainings/new.html.haml
%h1 New Workout

= render 'form'
%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/trainings/show.html.haml
%h1= @training.date
%p= @training.name
%p= @training.description 

%br/

= render "exercises/form"

= link_to "Back", trainings_path, class: "btn btn-default"
= link_to "Edit", edit_training_path, class: "btn btn-default"
= link_to "Delete", training_path, method: :delete, data:{confirm: "Are you sure"}, class: "btn btn-default"